language: java

notifications:
 email:
  - marcosalles@gmail.com
  - template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
   - "Change view : %{compare_url}"
   - "Build details : %{build_url}"

before_script:
 - ./scripts/mysql-setup.sh

script:
 - mvn clean jacoco:prepare-agent test jacoco:report > logs/build.log