language: java

notifications:
 email:
  recipients:
   marcosalles@gmail.com
  on_success: [always|never|change] # default: change
  on_failure: [always|never|change] # default: always
  template:
   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
   - "Change view : %{compare_url}"
   - "Build details : %{build_url}"

before_script:
 - ./scripts/mysql-setup.sh install

script:
 - mvn clean jacoco:prepare-agent test jacoco:report > logs/build.log

after_script:
 - ./scripts/mysql-setup.sh uninstall